//we don't have images for the greyed out characters

const characters = [
    "Ned Stark",
    "Jon Snow",
    "Robert Baratheon",
    "Robb Stark",
    "Arya Stark",
    "Yara Greyjoy",
    "Theon Greyjoy",
    // "Sansa Stark",
    "Daenerys Targaryen",
    "Bran Stark",
    "Hodor",
    "Khal Drogo",
    "Samwell Tarly",
    "Melisandre",
    "Stannis Baratheon",
    "Varys",
    // "The High Sparrow",
    "Brienne of Tarth",
    // "Margaery Tyrell",
    "Jorah Mormont",
    "Jaime Lannister",
    "Tywin Lannister",
    "Jaqen Hghar",
    "Ghost",
    "Tyrion Lannister",
    "Cersei Lannister",
    "Oberyn Martell",
    "Ygritte",
    "White Walker",
    "Gendry",
    "Grey Worm",
    "The Hound",
    "The Mountain",
    "Joffrey Baratheon",
    "Ramsey Bolton",
    "Petyr Baelish",
];
export default characters;
