//we don't have images for the greyed out characters

const characters = [
["Ned Stark",1],
["Jon Snow",2],
["Robert Baratheon",3],
["Robb Stark",4],
["Arya Stark",5],
["Yara Greyjoy",6],
["Theon Greyjoy",7],
["Daenerys Targaryen",8],
["Bran Stark",9],
["Hodor",10],
["Khal Drogo",11],
["Samwell Tarly",12],
["Melisandre",13],
["Stannis Baratheon",14],
["Varys",15],
["Brienne of Tarth",16],
["Jorah Mormont",17],
["Jaime Lannister",18],
["Tywin Lannister",19],
["Jaqen Hghar",20],
["Ghost",21],
["Tyrion Lannister",22],
["Cersei Lannister",23],
["Oberyn Martell",24],
["Ygritte",25],
["White Walker",26],
["Gendry",27],
["Grey Worm",28],
["The Hound",29],
["The Mountain",30],
["Joffrey Baratheon",31],
["Ramsey Bolton",32],
["Petyr Baelish",33]
];
export default characters;
